### ISSUE TITLE
blurayplayer does not work anymore

### ISSUE THREAD

**Issue by thawtes** [Taapat/enigma2-plugin-blurayplayer#19]
hello dear @Taapat 
Blurayplayer does not work after libblueray and libudfread update
see
https://github.com/oe-alliance/oe-alliance-core/commit/62936c8b184e239bbdf36505442f210a58da5be3

crash log
`06:55:28.8767 {   } Components/ActionMap.py:46 action action ->  SetupActions ok
06:55:28.8885 { D } Traceback (most recent call last):
06:55:28.8889 { D }   File "/usr/lib/enigma2/python/Components/ActionMap.py", line 48, in action
06:55:28.8894 { D }   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 299, in keyOk
06:55:28.8899 { D }   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 203, in save
06:55:28.8903 { D }   File "/usr/lib/enigma2/python/Screens/PluginBrowser.py", line 207, in run
06:55:28.8906 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/BlurayPlayer/plugin.py", line 9, in dirBrowser
06:55:28.8911 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/BlurayPlayer/BlurayPlayerDirBrowser.py", line 10, in <module>
06:55:28.8916 { D }   File "/usr/lib/enigma2/python/Plugins/Extensions/BlurayPlayer/BlurayUi.py", line 19, in <module>
06:55:28.8922 { D } ImportError: libbluray.so.1: cannot open shared object file: No such file or directory
06:55:28.8926 [ E ] python/python.cpp:209 call [ePyObject] (PyObject_CallObject(<bound method ActionMap.action of <Components.ActionMap.ActionMap instance at 0x5e067198>>,('SetupActions', 'ok')) failed)`

openatv 6.2
vuduo2

pls fixing, thank you

**Comment by Taapat** [comment]
This is not a plugin problem.
This is an openatv build system problem.
I assume they do not use a PR server and therefore need to increase the plugin version in feed after the 
libbluray update.

**Comment by Taapat** [comment]
You can try remove plugin, and after install plugin from feed.
