### ISSUE TITLE
Auto Audio Selection

### ISSUE THREAD

**Issue by thawtes** [Taapat/enigma2-plugin-blurayplayer#20]
hello @Taapat 

auto audio selection not working properly!
wrong choice of audio language...

my device vu+duo2
images openATV or openPLI

**Comment by Taapat** [comment]
Hi,
Can you describe in more detail.
Is the list of languages incorrect and does not match the real audio language?
Or that is on all bluray which do you try or on some?

Audio information is extracted from titles. Maybe they are wrong?
But it could only be for some bluray not for all.

**Comment by thawtes** [comment]
hi,
list of languages correct and match
but target audio language don't auto select from enigma2

sample;
[e2 auto audio language settings]
Audio 1 = Turkish
Audio 2 = English
....
[bluray list of languages]
1 Deutsch
2 Czech
3 English
4 Turkish
5 Serbian
6 Spanish
...
always work audio 1
whereas Turkish audio should work ?

**Comment by Taapat** [comment]
Thank you, clear.
In fact, auto language selection for m2ts files is not created in enigma.
However, if it was created, it might not work on the bluray.
I can try to find the time in creating it in the plugin.

**Comment by thawtes** [comment]
thanks
