### ISSUE TITLE
openatv 7.0 compatible

### ISSUE THREAD

**Issue by thawtes** [Taapat/enigma2-plugin-blurayplayer#23]
hello @Taapat 

please update this plugin for compatible openatv 7.0 (python3)

thank you

**Comment by Taapat** [comment]
Hi,
At this point I don't have time to test on a real openatv 7.0 image but you can try an untested branch python3: https://github.com/Taapat/enigma2-plugin-blurayplayer/commits/python3
If everything works I can merge it in the master.

**Comment by Taapat** [comment]
With last changes plugin is compatible with python3.
I tested on openatv 7.0 image.

**Comment by Taapat** [comment]
https://github.com/oe-alliance/oe-alliance-core/pull/734

**Comment by thawtes** [comment]
dear @Taapat thank you very much
