### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Spaeleus** [Taapat/enigma2-plugin-blurayplayer#28]
Hi!

Here my italian translation.

Thanks a lot again!

[BlurayPlayer-git151+51a8269-r1_cortexa15hf-neon-vfpv4-it.zip](https://github.com/Taapat/enigma2-plugin-blurayplayer/files/13625125/BlurayPlayer-git151%2B51a8269-r1_cortexa15hf-neon-vfpv4-it.zip)

**Comment by Taapat** [comment]
Thank you!
